name: Component - Container Apps Env

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'create'
        type: choice
        options:
        - create
        - destroy
      resource_group:
        description: 'Azure Resource Group Name'
        required: true
        default: 'ds1-rg'
      location:
        description: 'Azure Region'
        required: true
        default: 'eastus2'
      suffix:
        description: 'Unique Suffix'
        required: true
        default: 'ds1dev'

permissions:
  id-token: write
  contents: read

jobs:
  manage-host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Environment
        if: ${{ inputs.action == 'create' }}
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ inputs.resource_group }}
          template: ./infra/modules/host.bicep
          parameters: location=${{ inputs.location }} suffix=${{ inputs.suffix }}

      - name: Destroy Environment
        if: ${{ inputs.action == 'destroy' }}
        run: |
          RESOURCE_NAME="cae-${{ inputs.suffix }}"
          echo "⚠️ Deleting Container Apps Environment: $RESOURCE_NAME..."
          az containerapp env delete --name $RESOURCE_NAME --resource-group ${{ inputs.resource_group }} --yes --verbose
          echo "✅ Resource deleted."
